#ifndef CONFIG_H
#define CONFIG_H

#define FW_VERSION "1.0"

#define CHANNEL_COUNT 10

#define DEFAULT_STEP_DELAY 2000
#define DEFAULT_TARGET_CYCLES 500000
#define DEFAULT_MEASURE_INTERVAL 20000
#define DEFAULT_SAVE_INTERVAL 10

#define RUNTIME_SAVE_INTERVAL 60

#define DIR_LEFT 0
#define DIR_RIGHT 1

#endif